workflows:
  my-workflow:
    scripts:
      - name: Set up local.properties
        script: | 
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      - name: Build AAB with Flutter
        script: | 
          flutter build apk
    artifacts:
        - build/**/outputs/**/*.apk
        - build/**/outputs/**/mapping.txt
        - flutter_drive.log
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true 
    when:
      changeset:
        includes:
          - 'android/'
          - 'lib/'
          - 'assets/'
          - 'ios/'
          - 'pubspec.yaml'
          - 'codemagic.yaml'
